apiVersion: microcks.io/v1alpha1
kind: Microcks
metadata:
  name: microcks
spec:
  microcks:
    url: microcks.m2.minikube.local
    ingress:
      annotations:
        cert-manager.io/issuer: my-cert-issuer
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: nginx
    extraProperties:
      server:
        tomcat:
          remoteip:
            internal-proxies: 172.16.0.0/12
    openshift:
      route:
        enabled: false
  keycloak:
    url: keycloak.m2.minikube.local