apiVersion: microcks.io/v1alpha1
kind: Microcks
metadata:
  name: microcks
spec:
  version: 1.9.1
  microcks:
    url: microcks.m2.minikube.local
  keycloak:
    url: keycloak.m2.minikube.local
    privateUrl: http://microcks-keycloak.microcks2.svc.cluster.local:8080